#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
$APPDIR/java/bin/java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/AveragePointTracking.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/openkinect_processing.jar:$APPDIR/lib/video.jar:$APPDIR/lib/gst1-java-core-1.4.0.jar:$APPDIR/lib/jna.jar" AveragePointTracking "$@"
